/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WarrantyRouteImport } from './routes/warranty'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SolutionsRouteImport } from './routes/solutions'
import { Route as SitemapRouteImport } from './routes/sitemap'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as OurStoryRouteImport } from './routes/our-story'
import { Route as MaterialStandardsRouteImport } from './routes/material-standards'
import { Route as LifestyleRouteImport } from './routes/lifestyle'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as CraftsmanshipRouteImport } from './routes/craftsmanship'
import { Route as ConsultationRouteImport } from './routes/consultation'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServiceServiceIdRouteImport } from './routes/service.$serviceId'
import { Route as CategoryCategoryIdRouteImport } from './routes/category.$categoryId'
import { Route as CampaignsWeightlessPavilionRouteImport } from './routes/campaigns.weightless-pavilion'
import { Route as CampaignsSilentPromiseRouteImport } from './routes/campaigns.silent-promise'
import { Route as CampaignsLightAndSanctuaryRouteImport } from './routes/campaigns.light-and-sanctuary'

const WarrantyRoute = WarrantyRouteImport.update({
  id: '/warranty',
  path: '/warranty',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsRoute = SolutionsRouteImport.update({
  id: '/solutions',
  path: '/solutions',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapRoute = SitemapRouteImport.update({
  id: '/sitemap',
  path: '/sitemap',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const OurStoryRoute = OurStoryRouteImport.update({
  id: '/our-story',
  path: '/our-story',
  getParentRoute: () => rootRouteImport,
} as any)
const MaterialStandardsRoute = MaterialStandardsRouteImport.update({
  id: '/material-standards',
  path: '/material-standards',
  getParentRoute: () => rootRouteImport,
} as any)
const LifestyleRoute = LifestyleRouteImport.update({
  id: '/lifestyle',
  path: '/lifestyle',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const CraftsmanshipRoute = CraftsmanshipRouteImport.update({
  id: '/craftsmanship',
  path: '/craftsmanship',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsultationRoute = ConsultationRouteImport.update({
  id: '/consultation',
  path: '/consultation',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiceServiceIdRoute = ServiceServiceIdRouteImport.update({
  id: '/service/$serviceId',
  path: '/service/$serviceId',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoryCategoryIdRoute = CategoryCategoryIdRouteImport.update({
  id: '/category/$categoryId',
  path: '/category/$categoryId',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsWeightlessPavilionRoute =
  CampaignsWeightlessPavilionRouteImport.update({
    id: '/campaigns/weightless-pavilion',
    path: '/campaigns/weightless-pavilion',
    getParentRoute: () => rootRouteImport,
  } as any)
const CampaignsSilentPromiseRoute = CampaignsSilentPromiseRouteImport.update({
  id: '/campaigns/silent-promise',
  path: '/campaigns/silent-promise',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsLightAndSanctuaryRoute =
  CampaignsLightAndSanctuaryRouteImport.update({
    id: '/campaigns/light-and-sanctuary',
    path: '/campaigns/light-and-sanctuary',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/consultation': typeof ConsultationRoute
  '/craftsmanship': typeof CraftsmanshipRoute
  '/faq': typeof FaqRoute
  '/lifestyle': typeof LifestyleRoute
  '/material-standards': typeof MaterialStandardsRoute
  '/our-story': typeof OurStoryRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap': typeof SitemapRoute
  '/solutions': typeof SolutionsRoute
  '/terms': typeof TermsRoute
  '/warranty': typeof WarrantyRoute
  '/campaigns/light-and-sanctuary': typeof CampaignsLightAndSanctuaryRoute
  '/campaigns/silent-promise': typeof CampaignsSilentPromiseRoute
  '/campaigns/weightless-pavilion': typeof CampaignsWeightlessPavilionRoute
  '/category/$categoryId': typeof CategoryCategoryIdRoute
  '/service/$serviceId': typeof ServiceServiceIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/consultation': typeof ConsultationRoute
  '/craftsmanship': typeof CraftsmanshipRoute
  '/faq': typeof FaqRoute
  '/lifestyle': typeof LifestyleRoute
  '/material-standards': typeof MaterialStandardsRoute
  '/our-story': typeof OurStoryRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap': typeof SitemapRoute
  '/solutions': typeof SolutionsRoute
  '/terms': typeof TermsRoute
  '/warranty': typeof WarrantyRoute
  '/campaigns/light-and-sanctuary': typeof CampaignsLightAndSanctuaryRoute
  '/campaigns/silent-promise': typeof CampaignsSilentPromiseRoute
  '/campaigns/weightless-pavilion': typeof CampaignsWeightlessPavilionRoute
  '/category/$categoryId': typeof CategoryCategoryIdRoute
  '/service/$serviceId': typeof ServiceServiceIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/consultation': typeof ConsultationRoute
  '/craftsmanship': typeof CraftsmanshipRoute
  '/faq': typeof FaqRoute
  '/lifestyle': typeof LifestyleRoute
  '/material-standards': typeof MaterialStandardsRoute
  '/our-story': typeof OurStoryRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap': typeof SitemapRoute
  '/solutions': typeof SolutionsRoute
  '/terms': typeof TermsRoute
  '/warranty': typeof WarrantyRoute
  '/campaigns/light-and-sanctuary': typeof CampaignsLightAndSanctuaryRoute
  '/campaigns/silent-promise': typeof CampaignsSilentPromiseRoute
  '/campaigns/weightless-pavilion': typeof CampaignsWeightlessPavilionRoute
  '/category/$categoryId': typeof CategoryCategoryIdRoute
  '/service/$serviceId': typeof ServiceServiceIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/consultation'
    | '/craftsmanship'
    | '/faq'
    | '/lifestyle'
    | '/material-standards'
    | '/our-story'
    | '/privacy'
    | '/sitemap'
    | '/solutions'
    | '/terms'
    | '/warranty'
    | '/campaigns/light-and-sanctuary'
    | '/campaigns/silent-promise'
    | '/campaigns/weightless-pavilion'
    | '/category/$categoryId'
    | '/service/$serviceId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/consultation'
    | '/craftsmanship'
    | '/faq'
    | '/lifestyle'
    | '/material-standards'
    | '/our-story'
    | '/privacy'
    | '/sitemap'
    | '/solutions'
    | '/terms'
    | '/warranty'
    | '/campaigns/light-and-sanctuary'
    | '/campaigns/silent-promise'
    | '/campaigns/weightless-pavilion'
    | '/category/$categoryId'
    | '/service/$serviceId'
  id:
    | '__root__'
    | '/'
    | '/consultation'
    | '/craftsmanship'
    | '/faq'
    | '/lifestyle'
    | '/material-standards'
    | '/our-story'
    | '/privacy'
    | '/sitemap'
    | '/solutions'
    | '/terms'
    | '/warranty'
    | '/campaigns/light-and-sanctuary'
    | '/campaigns/silent-promise'
    | '/campaigns/weightless-pavilion'
    | '/category/$categoryId'
    | '/service/$serviceId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConsultationRoute: typeof ConsultationRoute
  CraftsmanshipRoute: typeof CraftsmanshipRoute
  FaqRoute: typeof FaqRoute
  LifestyleRoute: typeof LifestyleRoute
  MaterialStandardsRoute: typeof MaterialStandardsRoute
  OurStoryRoute: typeof OurStoryRoute
  PrivacyRoute: typeof PrivacyRoute
  SitemapRoute: typeof SitemapRoute
  SolutionsRoute: typeof SolutionsRoute
  TermsRoute: typeof TermsRoute
  WarrantyRoute: typeof WarrantyRoute
  CampaignsLightAndSanctuaryRoute: typeof CampaignsLightAndSanctuaryRoute
  CampaignsSilentPromiseRoute: typeof CampaignsSilentPromiseRoute
  CampaignsWeightlessPavilionRoute: typeof CampaignsWeightlessPavilionRoute
  CategoryCategoryIdRoute: typeof CategoryCategoryIdRoute
  ServiceServiceIdRoute: typeof ServiceServiceIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/warranty': {
      id: '/warranty'
      path: '/warranty'
      fullPath: '/warranty'
      preLoaderRoute: typeof WarrantyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions': {
      id: '/solutions'
      path: '/solutions'
      fullPath: '/solutions'
      preLoaderRoute: typeof SolutionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap': {
      id: '/sitemap'
      path: '/sitemap'
      fullPath: '/sitemap'
      preLoaderRoute: typeof SitemapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/our-story': {
      id: '/our-story'
      path: '/our-story'
      fullPath: '/our-story'
      preLoaderRoute: typeof OurStoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/material-standards': {
      id: '/material-standards'
      path: '/material-standards'
      fullPath: '/material-standards'
      preLoaderRoute: typeof MaterialStandardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lifestyle': {
      id: '/lifestyle'
      path: '/lifestyle'
      fullPath: '/lifestyle'
      preLoaderRoute: typeof LifestyleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/craftsmanship': {
      id: '/craftsmanship'
      path: '/craftsmanship'
      fullPath: '/craftsmanship'
      preLoaderRoute: typeof CraftsmanshipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consultation': {
      id: '/consultation'
      path: '/consultation'
      fullPath: '/consultation'
      preLoaderRoute: typeof ConsultationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/service/$serviceId': {
      id: '/service/$serviceId'
      path: '/service/$serviceId'
      fullPath: '/service/$serviceId'
      preLoaderRoute: typeof ServiceServiceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category/$categoryId': {
      id: '/category/$categoryId'
      path: '/category/$categoryId'
      fullPath: '/category/$categoryId'
      preLoaderRoute: typeof CategoryCategoryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns/weightless-pavilion': {
      id: '/campaigns/weightless-pavilion'
      path: '/campaigns/weightless-pavilion'
      fullPath: '/campaigns/weightless-pavilion'
      preLoaderRoute: typeof CampaignsWeightlessPavilionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns/silent-promise': {
      id: '/campaigns/silent-promise'
      path: '/campaigns/silent-promise'
      fullPath: '/campaigns/silent-promise'
      preLoaderRoute: typeof CampaignsSilentPromiseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns/light-and-sanctuary': {
      id: '/campaigns/light-and-sanctuary'
      path: '/campaigns/light-and-sanctuary'
      fullPath: '/campaigns/light-and-sanctuary'
      preLoaderRoute: typeof CampaignsLightAndSanctuaryRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConsultationRoute: ConsultationRoute,
  CraftsmanshipRoute: CraftsmanshipRoute,
  FaqRoute: FaqRoute,
  LifestyleRoute: LifestyleRoute,
  MaterialStandardsRoute: MaterialStandardsRoute,
  OurStoryRoute: OurStoryRoute,
  PrivacyRoute: PrivacyRoute,
  SitemapRoute: SitemapRoute,
  SolutionsRoute: SolutionsRoute,
  TermsRoute: TermsRoute,
  WarrantyRoute: WarrantyRoute,
  CampaignsLightAndSanctuaryRoute: CampaignsLightAndSanctuaryRoute,
  CampaignsSilentPromiseRoute: CampaignsSilentPromiseRoute,
  CampaignsWeightlessPavilionRoute: CampaignsWeightlessPavilionRoute,
  CategoryCategoryIdRoute: CategoryCategoryIdRoute,
  ServiceServiceIdRoute: ServiceServiceIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
